#pragma once

// Name: ManEater, Version: 1.0.0


/*!!DEFINE!!*/

/*!!HELPER_DEF!!*/

/*!!HELPER_INC!!*/

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace CG
{
//---------------------------------------------------------------------------
// Classes
//---------------------------------------------------------------------------

// AnimBlueprintGeneratedClass HumanBase_ABP.HumanBase_ABP_C
// 0x8781 (FullSize[0x9201] - InheritedSize[0x0A80])
class UHumanBase_ABP_C : public UME_AnimInstance_HumanNPC
{
public:
	struct FPointerToUberGraphFrame                    UberGraphFrame;                                            // 0x0A80(0x0008) (ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                              AnimGraphNode_Root;                                        // 0x0A88(0x0030)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_27;                          // 0x0AB8(0x00A0)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_26;                          // 0x0B58(0x00A0)
	struct FAnimNode_Slot                              AnimGraphNode_Slot_7;                                      // 0x0BF8(0x0048)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_33;                         // 0x0C40(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_32;                         // 0x0C68(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_31;                         // 0x0C90(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_30;                         // 0x0CB8(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_29;                         // 0x0CE0(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_28;                         // 0x0D08(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_27;                         // 0x0D30(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_26;                         // 0x0D58(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_25;                         // 0x0D80(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_24;                         // 0x0DA8(0x0028)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_57;                           // 0x0DD0(0x0078)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_24;                              // 0x0E48(0x0030)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_56;                           // 0x0E78(0x0078)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_23;                              // 0x0EF0(0x0030)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_55;                           // 0x0F20(0x0078)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_25;                          // 0x0F98(0x00A0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_21;                            // 0x1038(0x0028)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_24;                          // 0x1060(0x00A0)
	struct FAnimNode_RotationOffsetBlendSpace          AnimGraphNode_RotationOffsetBlendSpace_2;                  // 0x1100(0x0188)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_23;                         // 0x1288(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_22;                         // 0x12B0(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_21;                         // 0x12D8(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_20;                         // 0x1300(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_19;                         // 0x1328(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_18;                         // 0x1350(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_17;                         // 0x1378(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_16;                         // 0x13A0(0x0028)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_54;                           // 0x13C8(0x0078)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_22;                              // 0x1440(0x0030)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_53;                           // 0x1470(0x0078)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_21;                              // 0x14E8(0x0030)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_20;                            // 0x1518(0x0028)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_20;                              // 0x1540(0x0030)
	struct FAnimNode_StateMachine                      AnimGraphNode_StateMachine_12;                             // 0x1570(0x00B0)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_10;                         // 0x1620(0x00C0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_52;                           // 0x16E0(0x0078)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_23;                          // 0x1758(0x00A0)
	struct FAnimNode_Slot                              AnimGraphNode_Slot_6;                                      // 0x17F8(0x0048)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_19;                            // 0x1840(0x0028)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_19;                              // 0x1868(0x0030)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_15;                         // 0x1898(0x0028)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_51;                           // 0x18C0(0x0078)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_18;                              // 0x1938(0x0030)
	struct FAnimNode_StateMachine                      AnimGraphNode_StateMachine_11;                             // 0x1968(0x00B0)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_14;                         // 0x1A18(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_13;                         // 0x1A40(0x0028)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_17;                         // 0x1A68(0x00E0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_15;                          // 0x1B48(0x00B0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_50;                           // 0x1BF8(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_49;                           // 0x1C70(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_48;                           // 0x1CE8(0x0078)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_22;                          // 0x1D60(0x00A0)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_21;                          // 0x1E00(0x00A0)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_20;                          // 0x1EA0(0x00A0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_16;                         // 0x1F40(0x00E0)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_17;                              // 0x2020(0x0030)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_47;                           // 0x2050(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_46;                           // 0x20C8(0x0078)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_14;                          // 0x2140(0x00B0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_45;                           // 0x21F0(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_44;                           // 0x2268(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_43;                           // 0x22E0(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_42;                           // 0x2358(0x0078)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_13;                          // 0x23D0(0x00B0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_41;                           // 0x2480(0x0078)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_16;                              // 0x24F8(0x0030)
	struct FAnimNode_StateMachine                      AnimGraphNode_StateMachine_10;                             // 0x2528(0x00B0)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_12;                         // 0x25D8(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_11;                         // 0x2600(0x0028)
	struct FAnimNode_RotationOffsetBlendSpace          AnimGraphNode_RotationOffsetBlendSpace;                    // 0x2628(0x0188)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_40;                           // 0x27B0(0x0078)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_19;                          // 0x2828(0x00A0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_39;                           // 0x28C8(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_38;                           // 0x2940(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_37;                           // 0x29B8(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_36;                           // 0x2A30(0x0078)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_12;                          // 0x2AA8(0x00B0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_35;                           // 0x2B58(0x0078)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_15;                         // 0x2BD0(0x00E0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_11;                          // 0x2CB0(0x00B0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_10;                          // 0x2D60(0x00B0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_34;                           // 0x2E10(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_33;                           // 0x2E88(0x0078)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_18;                          // 0x2F00(0x00A0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_32;                           // 0x2FA0(0x0078)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_17;                          // 0x3018(0x00A0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_31;                           // 0x30B8(0x0078)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_16;                          // 0x3130(0x00A0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_30;                           // 0x31D0(0x0078)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_15;                              // 0x3248(0x0030)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_29;                           // 0x3278(0x0078)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_9;                          // 0x32F0(0x00C0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_14;                         // 0x33B0(0x00E0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_13;                         // 0x3490(0x00E0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_12;                         // 0x3570(0x00E0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_11;                         // 0x3650(0x00E0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_9;                           // 0x3730(0x00B0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_10;                         // 0x37E0(0x00E0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_9;                          // 0x38C0(0x00E0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_8;                          // 0x39A0(0x00E0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_8;                           // 0x3A80(0x00B0)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_14;                              // 0x3B30(0x0030)
	struct FAnimNode_StateMachine                      AnimGraphNode_StateMachine_9;                              // 0x3B60(0x00B0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_28;                           // 0x3C10(0x0078)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_10;                           // 0x3C88(0x00B8)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_15;                          // 0x3D40(0x00A0)
	struct FAnimNode_RefPose                           AnimGraphNode_LocalRefPose_6;                              // 0x3DE0(0x0018)
	struct FAnimNode_Slot                              AnimGraphNode_Slot_5;                                      // 0x3DF8(0x0048)
	struct FAnimNode_Slot                              AnimGraphNode_Slot_4;                                      // 0x3E40(0x0048)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_14;                          // 0x3E88(0x00A0)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_13;                          // 0x3F28(0x00A0)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_12;                          // 0x3FC8(0x00A0)
	struct FAnimNode_PoseSnapshot                      AnimGraphNode_PoseSnapshot_2;                              // 0x4068(0x0090)
	struct FAnimNode_ConvertComponentToLocalSpace      AnimGraphNode_ComponentToLocalSpace_7;                     // 0x40F8(0x0020)
	unsigned char                                      UnknownData_91M2[0x8];                                     // 0x4118(0x0008) MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
	struct FAnimNode_LookAt                            AnimGraphNode_LookAt_4;                                    // 0x4120(0x01B0)
	struct FAnimNode_ConvertLocalToComponentSpace      AnimGraphNode_LocalToComponentSpace_7;                     // 0x42D0(0x0020)
	struct FAnimNode_LookAt                            AnimGraphNode_LookAt_3;                                    // 0x42F0(0x01B0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_27;                           // 0x44A0(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_26;                           // 0x4518(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_25;                           // 0x4590(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_24;                           // 0x4608(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_23;                           // 0x4680(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_22;                           // 0x46F8(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_21;                           // 0x4770(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_20;                           // 0x47E8(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_19;                           // 0x4860(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_18;                           // 0x48D8(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_17;                           // 0x4950(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_16;                           // 0x49C8(0x0078)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_7;                           // 0x4A40(0x00B0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_6;                           // 0x4AF0(0x00B0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_5;                           // 0x4BA0(0x00B0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_15;                           // 0x4C50(0x0078)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_4;                           // 0x4CC8(0x00B0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_14;                           // 0x4D78(0x0078)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_3;                           // 0x4DF0(0x00B0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_2;                           // 0x4EA0(0x00B0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_13;                           // 0x4F50(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_12;                           // 0x4FC8(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_11;                           // 0x5040(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_10;                           // 0x50B8(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_9;                            // 0x5130(0x0078)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_13;                              // 0x51A8(0x0030)
	struct FAnimNode_StateMachine                      AnimGraphNode_StateMachine_8;                              // 0x51D8(0x00B0)
	struct FAnimNode_Slot                              AnimGraphNode_Slot_3;                                      // 0x5288(0x0048)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_9;                            // 0x52D0(0x00B8)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_18;                            // 0x5388(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_17;                            // 0x53B0(0x0028)
	struct FAnimNode_Slot                              AnimGraphNode_Slot_2;                                      // 0x53D8(0x0048)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_8;                          // 0x5420(0x00C0)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_7;                          // 0x54E0(0x00C0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_8;                            // 0x55A0(0x0078)
	struct FAnimNode_ConvertLocalToComponentSpace      AnimGraphNode_LocalToComponentSpace_6;                     // 0x5618(0x0020)
	struct FAnimNode_ConvertComponentToLocalSpace      AnimGraphNode_ComponentToLocalSpace_6;                     // 0x5638(0x0020)
	unsigned char                                      UnknownData_HXGX[0x8];                                     // 0x5658(0x0008) MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
	struct FAnimNode_LookAt                            AnimGraphNode_LookAt_2;                                    // 0x5660(0x01B0)
	struct FAnimNode_ConvertLocalToComponentSpace      AnimGraphNode_LocalToComponentSpace_5;                     // 0x5810(0x0020)
	struct FAnimNode_ConvertComponentToLocalSpace      AnimGraphNode_ComponentToLocalSpace_5;                     // 0x5830(0x0020)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_11;                          // 0x5850(0x00A0)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_6;                          // 0x58F0(0x00C0)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_8;                            // 0x59B0(0x00B8)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_16;                            // 0x5A68(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_15;                            // 0x5A90(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_10;                         // 0x5AB8(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_9;                          // 0x5AE0(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_8;                          // 0x5B08(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_7;                          // 0x5B30(0x0028)
	struct FAnimNode_ConvertComponentToLocalSpace      AnimGraphNode_ComponentToLocalSpace_4;                     // 0x5B58(0x0020)
	struct FAnimNode_ConvertLocalToComponentSpace      AnimGraphNode_LocalToComponentSpace_4;                     // 0x5B78(0x0020)
	struct FAnimNode_ModifyBone                        AnimGraphNode_ModifyBone_9;                                // 0x5B98(0x0108)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_7;                          // 0x5CA0(0x00E0)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_12;                              // 0x5D80(0x0030)
	struct FAnimNode_ConvertComponentToLocalSpace      AnimGraphNode_ComponentToLocalSpace_3;                     // 0x5DB0(0x0020)
	struct FAnimNode_ConvertLocalToComponentSpace      AnimGraphNode_LocalToComponentSpace_3;                     // 0x5DD0(0x0020)
	struct FAnimNode_ModifyBone                        AnimGraphNode_ModifyBone_8;                                // 0x5DF0(0x0108)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_6;                          // 0x5EF8(0x00E0)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_11;                              // 0x5FD8(0x0030)
	struct FAnimNode_RefPose                           AnimGraphNode_LocalRefPose_5;                              // 0x6008(0x0018)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_10;                              // 0x6020(0x0030)
	struct FAnimNode_StateMachine                      AnimGraphNode_StateMachine_7;                              // 0x6050(0x00B0)
	struct FAnimNode_ApplyAdditive                     AnimGraphNode_ApplyAdditive_4;                             // 0x6100(0x00C8)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_6;                          // 0x61C8(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_5;                          // 0x61F0(0x0028)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_7;                            // 0x6218(0x0078)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_9;                               // 0x6290(0x0030)
	struct FAnimNode_RefPose                           AnimGraphNode_LocalRefPose_4;                              // 0x62C0(0x0018)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_8;                               // 0x62D8(0x0030)
	struct FAnimNode_StateMachine                      AnimGraphNode_StateMachine_6;                              // 0x6308(0x00B0)
	struct FAnimNode_SequenceEvaluator                 AnimGraphNode_SequenceEvaluator;                           // 0x63B8(0x0048)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum;                             // 0x6400(0x00B0)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_7;                            // 0x64B0(0x00B8)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_14;                            // 0x6568(0x0028)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_5;                          // 0x6590(0x00E0)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_6;                            // 0x6670(0x00B8)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_4;                          // 0x6728(0x00E0)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_5;                            // 0x6808(0x00B8)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_10;                          // 0x68C0(0x00A0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_3;                          // 0x6960(0x00E0)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_9;                           // 0x6A40(0x00A0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_2;                          // 0x6AE0(0x00E0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer;                            // 0x6BC0(0x00E0)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_8;                           // 0x6CA0(0x00A0)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_5;                          // 0x6D40(0x00C0)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_4;                          // 0x6E00(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_3;                          // 0x6E28(0x0028)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_6;                            // 0x6E50(0x0078)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_7;                               // 0x6EC8(0x0030)
	struct FAnimNode_RefPose                           AnimGraphNode_LocalRefPose_3;                              // 0x6EF8(0x0018)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_6;                               // 0x6F10(0x0030)
	struct FAnimNode_StateMachine                      AnimGraphNode_StateMachine_5;                              // 0x6F40(0x00B0)
	struct FAnimNode_ApplyAdditive                     AnimGraphNode_ApplyAdditive_3;                             // 0x6FF0(0x00C8)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_13;                            // 0x70B8(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_12;                            // 0x70E0(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_11;                            // 0x7108(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_10;                            // 0x7130(0x0028)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_4;                          // 0x7158(0x00C0)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_2;                          // 0x7218(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult;                            // 0x7240(0x0028)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_5;                            // 0x7268(0x0078)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_5;                               // 0x72E0(0x0030)
	struct FAnimNode_RefPose                           AnimGraphNode_LocalRefPose_2;                              // 0x7310(0x0018)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_4;                               // 0x7328(0x0030)
	struct FAnimNode_StateMachine                      AnimGraphNode_StateMachine_4;                              // 0x7358(0x00B0)
	struct FAnimNode_ApplyAdditive                     AnimGraphNode_ApplyAdditive_2;                             // 0x7408(0x00C8)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_7;                           // 0x74D0(0x00A0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_4;                            // 0x7570(0x0078)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_6;                           // 0x75E8(0x00A0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_9;                             // 0x7688(0x0028)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_5;                           // 0x76B0(0x00A0)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_3;                               // 0x7750(0x0030)
	struct FAnimNode_StateMachine                      AnimGraphNode_StateMachine_3;                              // 0x7780(0x00B0)
	struct FAnimNode_LookAt                            AnimGraphNode_LookAt;                                      // 0x7830(0x01B0)
	struct FAnimNode_ApplyAdditive                     AnimGraphNode_ApplyAdditive;                               // 0x79E0(0x00C8)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_3;                            // 0x7AA8(0x0078)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_3;                          // 0x7B20(0x00C0)
	struct FAnimNode_RefPose                           AnimGraphNode_LocalRefPose;                                // 0x7BE0(0x0018)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_4;                            // 0x7BF8(0x00B8)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_8;                             // 0x7CB0(0x0028)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_2;                          // 0x7CD8(0x00C0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_7;                             // 0x7D98(0x0028)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_4;                           // 0x7DC0(0x00A0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_2;                            // 0x7E60(0x0078)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_3;                           // 0x7ED8(0x00A0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer;                              // 0x7F78(0x0078)
	struct FAnimNode_TwoWayBlend                       AnimGraphNode_TwoWayBlend;                                 // 0x7FF0(0x00C8)
	struct FAnimNode_PoseSnapshot                      AnimGraphNode_PoseSnapshot;                                // 0x80B8(0x0090)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_2;                               // 0x8148(0x0030)
	struct FAnimNode_StateMachine                      AnimGraphNode_StateMachine_2;                              // 0x8178(0x00B0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_6;                             // 0x8228(0x0028)
	struct FAnimNode_ModifyBone                        AnimGraphNode_ModifyBone_7;                                // 0x8250(0x0108)
	struct FAnimNode_ModifyBone                        AnimGraphNode_ModifyBone_6;                                // 0x8358(0x0108)
	struct FAnimNode_ModifyBone                        AnimGraphNode_ModifyBone_5;                                // 0x8460(0x0108)
	struct FAnimNode_ModifyBone                        AnimGraphNode_ModifyBone_4;                                // 0x8568(0x0108)
	struct FAnimNode_ModifyBone                        AnimGraphNode_ModifyBone_3;                                // 0x8670(0x0108)
	struct FAnimNode_ConvertComponentToLocalSpace      AnimGraphNode_ComponentToLocalSpace_2;                     // 0x8778(0x0020)
	struct FAnimNode_ConvertLocalToComponentSpace      AnimGraphNode_LocalToComponentSpace_2;                     // 0x8798(0x0020)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult;                                 // 0x87B8(0x0030)
	struct FAnimNode_StateMachine                      AnimGraphNode_StateMachine;                                // 0x87E8(0x00B0)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_3;                            // 0x8898(0x00B8)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_2;                           // 0x8950(0x00A0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_5;                             // 0x89F0(0x0028)
	struct FAnimNode_ModifyBone                        AnimGraphNode_ModifyBone_2;                                // 0x8A18(0x0108)
	struct FAnimNode_ConvertLocalToComponentSpace      AnimGraphNode_LocalToComponentSpace;                       // 0x8B20(0x0020)
	struct FAnimNode_ConvertComponentToLocalSpace      AnimGraphNode_ComponentToLocalSpace;                       // 0x8B40(0x0020)
	struct FAnimNode_TwoBoneIK                         AnimGraphNode_TwoBoneIK;                                   // 0x8B60(0x01E0)
	struct FAnimNode_Slot                              AnimGraphNode_Slot;                                        // 0x8D40(0x0048)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend;                            // 0x8D88(0x00C0)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_2;                            // 0x8E48(0x00B8)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_4;                             // 0x8F00(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_3;                             // 0x8F28(0x0028)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool;                             // 0x8F50(0x00A0)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose;                              // 0x8FF0(0x00B8)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_2;                             // 0x90A8(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose;                               // 0x90D0(0x0028)
	struct FAnimNode_ModifyBone                        AnimGraphNode_ModifyBone;                                  // 0x90F8(0x0108)
	bool                                               bPassengerGoToMovingVehicle;                               // 0x9200(0x0001) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)


	static UClass* StaticClass()
	{
		static auto ptr = UObject::FindClass("AnimBlueprintGeneratedClass HumanBase_ABP.HumanBase_ABP_C");
		return ptr;
	}



	void AnimGraph(struct FPoseLink* AnimGraph);
	void GetRandomBlendspace(class UBlendSpace** BlendSpace, TArray<class UBlendSpace*>* Array);
	void ChangePointingBool();
	class UAnimMontage* BumpAnimationToPlay(float HitFromAngle);
	void AnimNotify_StartAdditiveFiring();
	void K2_Reset();
	void ExecuteUbergraph_HumanBase_ABP(int EntryPoint);
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
